### PR TITLE
Add Bitwise operators

### PR DESCRIPTION
**Pull request by jcpst**
I was very pleased to find this project, it was almost exactly what I was looking for. One thing I was missing was bitwise operators, so I implemented them. If this isn't what you want for ketos, go ahead and close the PR.

My main concern is in the naming of the ketos functions: I see there is a tendency to use terse function names. so I made AND `&` and OR `|`. For XOR, I went with `bit-xor` since `^` is already being used for exponentiation. I considered naming the others `bit-and` and `bit-or`, but it didn't seem to be consistent with the shift functions. 

Since it's pre `1.0` software, I would assume there's some flexibility. I imagined you could:

* rename `^` to `pow` (Maybe even stick it in the math module) and use `&`, `|` and `^` for bitwise. 
* all three could be named `bit-` while considering using something like `shiftl` and `shiftr`

If you're interested, but would like some changes, please let me know! Thank you for building this project.

### CODE REVIEW

**Comment by murarth** [comment]
As I recall, the reason I hadn't added these operators myself was because I wasn't sure, conceptually, what one should expect of the functionality of bitwise operators on signed, arbitrary-precision integers. They seem less obvious and intuitive than their fixed-precision counterparts. But I suppose whatever the `num` people worked out for the `BigInt` implementation probably makes the most sense.

I have a few issues, though:

* Why implement these operators with `usize` parameter? `num-bigint` provides implementations for `BitAnd<BigInt>`.
* I agree with your concern about the inconsistent naming. I think the best option would be using `bit&`, `bit|`, `bit^` (and we could even add `bit!` for the `Not` operator).
* The functions could be changed to accept an arbitrary number of integer arguments, the way `+` and some arithmetic operators do. This seems most useful for `bit|`, but it could be done for `bit&` and `bit^`, as well.

**Comment by jcpst** [comment]
* No good reason why used `usize`. I was trying a few things out while getting it to compile. Updated to `BigInt`
* I like those. Updated names
* So far, updated `bit|` to accept an arbitrary number of args. 
* Added `bit!` boilerplate, but not yet implemented.

**Comment by murarth** [comment]
Sorry, my comment about `BigInt` was unclear. What I meant was to use the `BigInt` bitwise operator implementations to implement `BitAnd<Integer> for Integer`. Then, `Integer` value bitwise operators can be used directly, without conversion to `u32`; this also eliminates the overflow condition of bitwise operators.

I took a look at my code for `Integer` operator trait implementation and saw that it needed some clean-up, so I did that and added the trait implementations for bitwise operators, as well. This should make the addition of the bitwise functions easier.

**Comment by jcpst** [comment]
Thanks for implementing those traits on that refactor. I have it working, let me know if needs any changes.

**Comment by murarth** [comment]
Looks good. Just rebase onto `master` and squash into one commit and I'll merge.

**Comment by jcpst** [comment]
Great. thanks!

**Pull request merged**
